Master sooyong
tndyd5390/java-racingcar-precourse pull request #1
Opened 2021-11-08 08:14 UTC by tndyd5390

2021-11-08 08:40 UTC, moonjuhyeon requested changes
전체적으로 MVC 패턴을 너무 의식하여 작성한거 같습니다.
VC는 static한 객체이기 때문에 별다른 책임을 부여하지 않아도 됩니다.
모델은 각자 객체의 책임을 부여해서 작성해야 될 것 같습니다.

또한 레이싱게임 객체 또는 결과 객체와 같이 기능을 세분화해서 객체에게 책임을 부여할 수 있을 것 같아보입니다.
코멘트 확인해 주시고, 수정을 위한 리퀘스트 체인지 하겠습니다.

2021-11-08 08:40 UTC, moonjuhyeon commented on src/main/java/racinggame/Application.java
>          // TODO 자동차 경주 게임 구현
요런건 구현이 끝나면 지워주는 센스

2021-11-08 08:40 UTC, moonjuhyeon commented on src/main/java/racinggame/ds/Car.java
> +  private int position;
```suggestion
  private final String name;
  private final int position;
```
객체의 상태를 final로 선언해주면 더 좋습니다

2021-11-08 08:40 UTC, moonjuhyeon commented on src/main/java/racinggame/ds/Car.java
> +  }
set get은 피해주세요

2021-11-08 08:40 UTC, moonjuhyeon commented on src/main/java/racinggame/service/RacingGameService.java
> +  }
자동차 이름 예외에 대한 책임은 Car 객체에게 있습니다 .
Service에게 모델을 호출하여 로직을 수행하는 것 이상의 책임은 너무 합니다.

2021-11-08 08:40 UTC, moonjuhyeon commented on src/main/java/racinggame/view/InputView.java
> +    return Integer.parseInt(Console.readLine());
이부분에서 숫자가 아닌 다른 입력으로
NumberFormatExcepion이 발생한다면 레이싱 게임을 진행할 수 없지 않을까요?
시도할 회수 또한 다른 객체에게 책임을 부여해야 한다고 생각합니다.

2021-11-08 08:40 UTC, moonjuhyeon commented on src/test/java/racinggame/CarTest.java
> +public class CarTest {
TDD를 이용한 테스트에서 가장 중요한 것은 실패하는 케이스를 먼저 작성하는 것입니다.
현재 테스트 케이스들은 전부 성공하는 케이스만 있어요

2021-11-08 08:40 UTC, moonjuhyeon commented on src/main/java/racinggame/ds/Cars.java
> +  }
Cars 객체는 생성될때 어떤 자동차를 만들어라 라는 메시지를 가지고 생성되어야 하지 않을까요?
이런식으로 Cars 객체의 상태를 무분별하게 바꿀 수 있다면, 불완전한 객체를 사용하게 됩니다.

2021-11-09 00:20 UTC, tndyd5390 commented on src/main/java/racinggame/ds/Car.java
> +  private int position;
position은 지속적으로 값이 변경되는 변수인데 final이 괜찮을까요??

2021-11-09 08:31 UTC, tndyd5390 commented on src/main/java/racinggame/ds/Car.java
> +  private int position;
position은 변하기 때문에 final을 주지 않았고 이름은 final로 수정하였습니다.

2021-11-09 08:32 UTC, tndyd5390 commented on src/main/java/racinggame/ds/Car.java
> +  }
set은 최대한 지양하는 방향으로 수정하였습니다.

2021-11-09 08:32 UTC, tndyd5390 commented on src/main/java/racinggame/service/RacingGameService.java
> +  }
이름 예외에 대한 책임을 Car에서 질수 있도록 수정하였습니다.

2021-11-09 08:32 UTC, tndyd5390 commented on src/main/java/racinggame/view/InputView.java
> +    return Integer.parseInt(Console.readLine());
InputValidator 클래스를 추가하여 입력값을 검증하도록 수정하였습니다.

2021-11-09 08:36 UTC, tndyd5390 commented on src/main/java/racinggame/ds/Cars.java
> +  }
addCar메소드와 setter를 삭제하였습니다.

2021-11-09 09:06 UTC, moonjuhyeon requested changes
클래스를 분리하려는 노력이 매우 돋보 였습니다. 💯 
조금 아쉬운 마음에 몇가지 코멘트 더 달았습니다. 확인해주세요 👍

2021-11-09 09:06 UTC, moonjuhyeon commented on src/main/java/racinggame/racingGame/RacingGameService.java
> +  }
자동차 생성에 대한 책임은 레이싱서비스에게 존재하는 건가요??
Cars 객체의 책임이 전혀 존재하지 않는 것 같습니다.

2021-11-09 09:06 UTC, moonjuhyeon commented on src/main/java/racinggame/racingGame/RacingGameService.java
> +  }
자동차를 움직이는 것 또한 Cars 객체에 책임이 있다고 생각하는데, 수용님은 어떻게 생각하시나요?

2021-11-09 09:06 UTC, moonjuhyeon commented on src/main/java/racinggame/racingGame/RacingGameService.java
> +}
위와 동일합니다.

2021-11-09 09:06 UTC, moonjuhyeon commented on src/main/java/racinggame/view/InputValidator.java
> +public class InputValidator {
입력 값에 대한 확인을 Validator가 가지는 것으로 생각하신 것 같은데,
자동차 이름에 대한 책임은 Car에게 주는 것이 어떨까요?

2021-11-09 09:06 UTC, moonjuhyeon commented on src/main/java/racinggame/view/InputView.java
> +    inputValidator.isCarNameValidated(carName);
View는 값을 받고 보여주는 역할만 해야 한다고 생각합니다.

2021-11-09 09:06 UTC, moonjuhyeon commented on src/main/java/racinggame/racingGame/RacingGameResult.java
> +  private final Cars cars;
레이싱게임결과 객체은 자동차 일급 콜렉션에 의존성이 높아 보이는데,
레이싱게임결과 객체가 Cars를 상태로 가지고 있어야 할까요?
RacingGameResult이라는 자동차게임 결과의 책임을 가지는 클래스로 분리하였는데, 다시 내부에 들어오게 된 것 같아요.

2021-11-10 02:46 UTC, tndyd5390 commented on src/main/java/racinggame/view/InputValidator.java
> +public class InputValidator {
자동차 이름에 대한 책임은 현재 자동차가 가지고 있으며 위 InputValidator에서 검증하는 것은 구분자고 ','가 입력이 되었는지, 차의 이름이 2개이상 입력이 되었는지 확인하는 용도입니다.

2021-11-10 07:42 UTC, tndyd5390 commented on src/main/java/racinggame/racingGame/RacingGameService.java
> +  }
cars 객체에서 생성을 책임지도록 변경하였습니다.

2021-11-10 07:42 UTC, tndyd5390 commented on src/main/java/racinggame/racingGame/RacingGameService.java
> +  }
저도 동의합니다. 움직이는 동작을 Cars 객체로 이동하였습니다.

2021-11-10 07:43 UTC, tndyd5390 commented on src/main/java/racinggame/view/InputValidator.java
> +public class InputValidator {
InputValidator의 책임을 대폭 없애고 Car, Cars 객에체서 입력값에 대한 확인을 하도록 변경하였습니다. 그러나 입력값이 숫자인지 문자인지 판단하는 부분에서는 Car나 Cars의 책임이 아니라고 판단하여 InputValidator에 남겨두었습니다.

2021-11-10 07:44 UTC, tndyd5390 commented on src/main/java/racinggame/view/InputView.java
> +    inputValidator.isCarNameValidated(carName);
값을 받고 보여주는 역할로만 변경하였습니다.

2021-11-10 07:48 UTC, tndyd5390 commented on src/main/java/racinggame/racingGame/RacingGameResult.java
> +  private final Cars cars;
result 객체가 Cars 객체를 가지지 않도록 수정하였습니다.

2021-11-10 08:11 UTC, moonjuhyeon approved these changes
고생 많이 하셨습니다 👍 
아쉬운 마음에 몇 가지 코멘트 남겼습니다.
Approve 누를게요 💯  LGTM !

2021-11-10 08:11 UTC, moonjuhyeon commented on src/main/java/racinggame/controller/RacingGameController.java
> +  }
저는 `RacingGame` 이라는 모델을 만들어서 `Cars`와 `round`를 통해 게임을 진행할 것 같아요.
컨트롤러에서 게임 진행을 위한 반복문 사용은 좋지 않다고 생각합니다.

2021-11-10 08:11 UTC, moonjuhyeon commented on src/main/java/racinggame/ds/Car.java
> +}
정적팩토리메소드로 객체 생성을 제어하셨는데, 빌더 패턴이 존재하는 이유를 알 수 있을까요??

2021-11-10 08:11 UTC, moonjuhyeon commented on src/main/java/racinggame/ds/Cars.java
> +  }
Random을 외부에서 레이싱게임이 진행할 때 주입을 한다면, Cars에 대한 테스트가 더 개발자의 의도대로 될 거 같아요.

2021-11-11 05:08 UTC, tndyd5390 commented on src/main/java/racinggame/controller/RacingGameController.java
> +  }
RacingGame 모델 추가하였습니다.

2021-11-11 07:31 UTC, tndyd5390 commented on src/main/java/racinggame/ds/Car.java
> +}
빌더패턴 삭제하였습니다.

2021-11-11 08:19 UTC, merged